apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastify-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - host: fastify.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastify-service
                port:
                  number: 80
